"""Safe ZIP creation and extraction helpers.

Both directions are hardened against the classic archive attacks:

* **Creation** never follows a symlink (a link to ``/etc/passwd`` inside a
  workspace would otherwise be archived *by content*), never stores an absolute
  or traversing member name, and is bounded in entry count and total bytes.
* **Extraction** validates every member *before* writing anything: no
  traversal, no absolute paths, no symlinks, no device/special entries, and a
  bound on both the per-member and total uncompressed size (zip-bomb guard).

Member names are always stored POSIX-style so archives built on Windows extract
correctly everywhere.
"""

import os
import stat
import zipfile
from pathlib import Path, PurePosixPath
from typing import Iterable, Optional, Set, Union

from app.utils.filesystem import is_within, normalize_path

#: Hard caps applied to both directions.  Generous for a real LaTeX project
#: (a few hundred files, tens of MB) while still bounding a hostile archive.
MAX_ENTRIES = 10_000
MAX_TOTAL_BYTES = 500 * 1024 * 1024   # 500 MB uncompressed
MAX_MEMBER_BYTES = 200 * 1024 * 1024  # 200 MB for any single member

#: LaTeX build artefacts.  They are regenerated by ``latexmk`` and must not be
#: shipped: a stale ``.aux``/``.fdb_latexmk`` from the server makes a fresh
#: extraction fail or silently compile against outdated cross-references.
LATEX_BUILD_SUFFIXES: Set[str] = {
    ".aux", ".log", ".out", ".fls", ".fdb_latexmk", ".toc", ".lof", ".lot",
    ".blg", ".nav", ".snm", ".vrb", ".synctex", ".synctex.gz", ".bcf",
    ".run.xml", ".idx", ".ilg", ".ind", ".glo", ".gls", ".xdv", ".dvi",
}


class UnsafeArchiveError(Exception):
    """Raised when an archive member (in or out) fails a safety check."""


def _is_symlink_member(member: zipfile.ZipInfo) -> bool:
    """True when the ZIP entry carries UNIX symlink mode bits."""
    mode = member.external_attr >> 16
    return stat.S_ISLNK(mode)


def _is_special_member(member: zipfile.ZipInfo) -> bool:
    """True for block/char devices, FIFOs and sockets (never legitimate here)."""
    mode = member.external_attr >> 16
    if not mode:
        return False
    return bool(
        stat.S_ISBLK(mode) or stat.S_ISCHR(mode)
        or stat.S_ISFIFO(mode) or stat.S_ISSOCK(mode)
    )


def _member_is_safe_name(name: str) -> bool:
    """True when a member name is a plain relative path with no traversal."""
    if not name or "\x00" in name:
        return False
    # Windows-created archives may use backslashes; normalise before checking.
    normalised = name.replace("\\", "/")
    pure = PurePosixPath(normalised)
    if pure.is_absolute():
        return False
    # Drive-letter prefix ("C:/x") -- PurePosixPath does not treat it as absolute.
    if len(normalised) >= 2 and normalised[1] == ":":
        return False
    return ".." not in pure.parts


def validate_archive_members(archive_path: Union[str, Path],
                             dest_dir: Union[str, Path]) -> None:
    """Validate every member of *archive_path* against *dest_dir*.

    Raises :class:`UnsafeArchiveError` on the first unsafe member.  Nothing is
    written to disk by this function -- it is a pure pre-flight check so a
    hostile archive is rejected before any bytes land.
    """
    dest_abs = Path(os.path.abspath(str(dest_dir)))
    total = 0
    with zipfile.ZipFile(archive_path, "r") as zf:
        members = zf.infolist()
        if len(members) > MAX_ENTRIES:
            raise UnsafeArchiveError(
                f"Archive contains {len(members)} entries; the limit is {MAX_ENTRIES}."
            )
        for member in members:
            name = member.filename
            if not _member_is_safe_name(name):
                raise UnsafeArchiveError(
                    f"Archive member has an unsafe path (traversal or absolute): {name!r}"
                )
            if _is_symlink_member(member):
                raise UnsafeArchiveError(
                    f"Archive contains a symbolic link, which is not allowed: {name!r}"
                )
            if _is_special_member(member):
                raise UnsafeArchiveError(
                    f"Archive contains a special file, which is not allowed: {name!r}"
                )
            if member.file_size > MAX_MEMBER_BYTES:
                raise UnsafeArchiveError(
                    f"Archive member {name!r} expands to {member.file_size} bytes, "
                    f"over the {MAX_MEMBER_BYTES} byte per-file limit."
                )
            total += member.file_size
            if total > MAX_TOTAL_BYTES:
                raise UnsafeArchiveError(
                    "Archive expands beyond the "
                    f"{MAX_TOTAL_BYTES // (1024 * 1024)} MB total size limit."
                )
            # Belt and braces: the resolved destination must stay inside dest.
            target = Path(os.path.abspath(
                str(dest_abs / name.replace("\\", "/"))
            ))
            if not is_within(dest_abs, target):
                raise UnsafeArchiveError(
                    f"Archive member would be written outside the destination: {name!r}"
                )


def zip_directory(
    dir_path: Union[str, Path],
    zip_file_path: Union[str, Path],
    exclude_suffixes: Optional[Iterable[str]] = None,
    exclude_names: Optional[Iterable[str]] = None,
    include_hidden: bool = False,
) -> Path:
    """Zip the *contents* of a directory into a ZIP archive, safely.

    Symlinks (files and directories alike) are skipped rather than followed, so
    a link planted inside the source tree cannot pull unrelated server files
    into the archive.  Entries are written in sorted order for deterministic
    output, and member names are stored POSIX-style relative to *dir_path*.

    Args:
        dir_path: Directory whose contents are archived.
        zip_file_path: Destination ``.zip`` path.
        exclude_suffixes: Lower-case suffixes to omit (e.g. build artefacts).
        exclude_names: Exact file names to omit.
        include_hidden: When False (default) dot-files and dot-directories are
            skipped.

    Returns:
        The path to the written archive.
    """
    src_dir = normalize_path(dir_path)
    archive_path = normalize_path(zip_file_path)

    if not src_dir.exists() or not src_dir.is_dir():
        raise FileNotFoundError(
            f"Source directory does not exist or is not a directory: {src_dir}"
        )

    skip_suffixes = {s.lower() for s in (exclude_suffixes or ())}
    skip_names = set(exclude_names or ())

    archive_path.parent.mkdir(parents=True, exist_ok=True)

    written = 0
    total_bytes = 0
    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for root, dirs, files in os.walk(src_dir, followlinks=False):
            root_path = Path(root)
            # Prune symlinked and (optionally) hidden directories in place so
            # os.walk never descends into them.
            dirs[:] = sorted(
                d for d in dirs
                if not (root_path / d).is_symlink()
                and (include_hidden or not d.startswith("."))
            )
            for name in sorted(files):
                file_path = root_path / name
                if file_path.is_symlink():
                    continue  # never follow a link out of the tree
                if not include_hidden and name.startswith("."):
                    continue
                if name in skip_names:
                    continue
                suffix = file_path.suffix.lower()
                # ".synctex.gz" style double suffixes need a name-level check.
                double = "".join(file_path.suffixes[-2:]).lower()
                if suffix in skip_suffixes or double in skip_suffixes:
                    continue
                try:
                    if not file_path.is_file():
                        continue  # FIFOs, sockets, vanished files
                    size = file_path.stat().st_size
                except OSError:
                    continue

                written += 1
                total_bytes += size
                if written > MAX_ENTRIES:
                    raise UnsafeArchiveError(
                        f"Refusing to archive more than {MAX_ENTRIES} files."
                    )
                if total_bytes > MAX_TOTAL_BYTES:
                    raise UnsafeArchiveError(
                        "Refusing to archive more than "
                        f"{MAX_TOTAL_BYTES // (1024 * 1024)} MB."
                    )

                # Defence in depth: the file must genuinely live under src_dir.
                if not is_within(src_dir, file_path):
                    continue
                rel = file_path.relative_to(src_dir)
                zip_file.write(file_path, rel.as_posix())

    return archive_path


def extract_zip(zip_file_path: Union[str, Path],
                extract_dir: Union[str, Path]) -> Path:
    """Extract a ZIP archive into a destination directory, safely.

    Every member is validated first (traversal, absolute paths, symlinks,
    special files, per-member and total size).  Extraction is then performed
    member by member -- ``ZipFile.extractall`` is deliberately not used, since
    it honours whatever names the archive carries.

    Raises:
        UnsafeArchiveError: if any member fails a safety check.
    """
    archive_path = normalize_path(zip_file_path)
    dest_dir = normalize_path(extract_dir)

    if not archive_path.exists() or not archive_path.is_file():
        raise FileNotFoundError(
            f"Zip file does not exist or is not a file: {archive_path}"
        )
    if not zipfile.is_zipfile(archive_path):
        raise UnsafeArchiveError("The file is not a valid ZIP archive.")

    dest_dir.mkdir(parents=True, exist_ok=True)

    # Pre-flight: reject the whole archive before writing a single byte.
    validate_archive_members(archive_path, dest_dir)

    with zipfile.ZipFile(archive_path, "r") as zf:
        for member in zf.infolist():
            name = member.filename.replace("\\", "/")
            target = Path(os.path.abspath(str(dest_dir / name)))
            if not is_within(dest_dir, target):
                raise UnsafeArchiveError(
                    f"Refusing to write member outside destination: {name!r}"
                )

            if member.is_dir() or name.endswith("/"):
                target.mkdir(parents=True, exist_ok=True)
                continue

            target.parent.mkdir(parents=True, exist_ok=True)
            # An existing symlink at the target would redirect the write;
            # remove it so the bytes land where we validated they would.
            if target.is_symlink():
                target.unlink()
            with zf.open(member, "r") as source, open(target, "wb") as out:
                written = 0
                while True:
                    chunk = source.read(64 * 1024)
                    if not chunk:
                        break
                    written += len(chunk)
                    if written > MAX_MEMBER_BYTES:
                        raise UnsafeArchiveError(
                            f"Member {name!r} exceeded the per-file size limit "
                            "while extracting (declared size was understated)."
                        )
                    out.write(chunk)

    return dest_dir
