"""Package a completed job's LaTeX project into one self-contained ZIP.

The pipeline already assembles a complete, compilable project in the job's
``rendered/`` directory:

* ``TemplateManager.prepare_workspace`` copies **every** file of the selected
  template there (``.cls``, ``.sty``, ``.bst``, ``.bib``, logos, fonts, and any
  subdirectories the template ships);
* ``PipelineService.load_template`` copies the extracted document media into
  ``rendered/media/``;
* ``LatexRenderer`` writes ``main.tex`` there and the header reconstructor adds
  whatever generated assets it produces;
* ``LatexCompiler`` compiles with ``cwd=rendered/``.

So ``rendered/`` *is* the project, for every template, and the correct package
is a faithful copy of that tree.  This module therefore archives the whole
directory rather than hand-picking file types -- a whitelist is exactly how
"hidden dependencies" (a ``.clo`` option file, an ``.fd`` font definition, a
nested ``figures/`` folder) get dropped.

Only two categories are removed, both regenerated by ``latexmk``:

* LaTeX build artefacts (``.aux``, ``.log``, ``.fls``, ...) -- shipping a stale
  ``.aux`` makes a fresh extraction compile against outdated cross-references;
* the compiled ``main.pdf`` itself, which is the *output*, not a source.

``.bbl`` is a deliberate exception: it is dropped only when a ``.bib`` is
present (``latexmk`` will rebuild it); with no ``.bib`` in the project the
``.bbl`` is the only copy of the bibliography and must travel with it.
"""

import shutil
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from app.services.job_manager import JobManager
from app.utils.filesystem import is_within
from app.utils.logger import get_job_logger
from app.utils.zip_utils import LATEX_BUILD_SUFFIXES, zip_directory


class ProjectPackagerError(Exception):
    """Raised when a job's LaTeX project cannot be packaged."""


class ProjectPackager:
    """Builds the downloadable ZIP of a job's complete LaTeX project."""

    def __init__(self, job_manager: Optional[JobManager] = None) -> None:
        self.job_manager = job_manager or JobManager()

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    @staticmethod
    def _exclusions(rendered_dir: Path, tex_stem: str) -> Tuple[set, set]:
        """Return (suffixes, names) to omit from the archive for this project."""
        suffixes = set(LATEX_BUILD_SUFFIXES)

        # Keep the .bbl when there is no .bib to regenerate it from.
        has_bib = any(rendered_dir.rglob("*.bib"))
        if has_bib:
            suffixes.add(".bbl")

        # The compiled PDF of the manuscript is output, not source.  Other PDFs
        # in the tree are graphics and must be kept, so this is a name match,
        # never a suffix match.
        names = {f"{tex_stem}.pdf"}
        return suffixes, names

    def _dependency_report(self, main_tex: Path, rendered_dir: Path) -> Dict:
        """Resolve every dependency ``main.tex`` references against the project.

        Uses the compiler's own resolution rules so the answer matches what
        ``latexmk`` will actually do after extraction.
        """
        from app.compiler.latex_compiler import LatexCompiler

        source = main_tex.read_text(encoding="utf-8", errors="replace")
        bundled: List[str] = []
        from_tex_install: List[str] = []
        missing: List[str] = []
        for kind, target in LatexCompiler._extract_dependencies(source):
            status = LatexCompiler._resolve_dependency(kind, target, rendered_dir)
            label = f"{kind} -> {target}"
            if status == "local":
                bundled.append(label)
            elif status == "system":
                from_tex_install.append(label)
            elif status == "missing":
                missing.append(label)
        return {
            "bundled_in_zip": sorted(bundled),
            "provided_by_tex_installation": sorted(from_tex_install),
            "unresolved": sorted(missing),
        }

    @staticmethod
    def _write_readme(rendered_dir: Path, report: Dict, tex_name: str) -> None:
        """Drop a short build note next to the sources (overwritten each run)."""
        lines = [
            "This archive is a complete, self-contained LaTeX project.",
            "",
            "To build it:",
            "",
            f"    latexmk -pdf {tex_name}",
            "",
            f"The entry point is {tex_name}. Every class, style, bibliography,",
            "font and image file the document references is included, with the",
            "original folder structure preserved. LaTeX build artefacts have",
            "been removed so the first build starts clean.",
            "",
        ]
        if report.get("provided_by_tex_installation"):
            lines.append(
                "The following are standard packages supplied by your TeX "
                "distribution rather than bundled here:"
            )
            lines.append("")
            lines.extend(
                f"  - {item}" for item in report["provided_by_tex_installation"]
            )
            lines.append("")
        if report.get("unresolved"):
            lines.append(
                "NOTE: these references could not be resolved locally or in a "
                "TeX installation and may need to be installed:"
            )
            lines.append("")
            lines.extend(f"  - {item}" for item in report["unresolved"])
            lines.append("")
        (rendered_dir / "BUILD.txt").write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def build_project_zip(self, job_id: str) -> Tuple[Path, Path, Dict]:
        """Build the project ZIP for *job_id*.

        Returns:
            ``(zip_path, temp_dir, report)`` -- *temp_dir* is a freshly created
            directory that the caller **must** delete once the response has been
            sent (the API layer attaches it to a BackgroundTask).

        Raises:
            ProjectPackagerError: if the job has no rendered project yet.
        """
        logger = get_job_logger(job_id, "system")
        job_dir = self.job_manager._get_job_dir(job_id)
        rendered_dir = job_dir / "rendered"

        if not rendered_dir.is_dir():
            raise ProjectPackagerError(
                "No LaTeX project available for this job. Run the compile stage first."
            )
        # The rendered directory must genuinely sit inside the job workspace --
        # a symlinked 'rendered' would otherwise package an arbitrary directory.
        if rendered_dir.is_symlink() or not is_within(job_dir, rendered_dir.resolve()):
            raise ProjectPackagerError("The job workspace layout is invalid.")

        main_tex = rendered_dir / "main.tex"
        if not main_tex.is_file():
            raise ProjectPackagerError(
                "main.tex has not been generated for this job. Run the compile "
                "stage first."
            )

        report = self._dependency_report(main_tex, rendered_dir)
        try:
            self._write_readme(rendered_dir, report, main_tex.name)
        except OSError as exc:  # a missing build note must never fail the download
            logger.warning("Could not write BUILD.txt into the project: %s", exc)

        suffixes, names = self._exclusions(rendered_dir, main_tex.stem)

        # Build into a private temp directory so two concurrent downloads of the
        # same job never write to one another's archive.
        temp_dir = Path(tempfile.mkdtemp(prefix=f"j2l_project_{job_id[:8]}_"))
        zip_path = temp_dir / "project.zip"
        try:
            zip_directory(
                rendered_dir,
                zip_path,
                exclude_suffixes=suffixes,
                exclude_names=names,
            )
        except Exception:
            shutil.rmtree(temp_dir, ignore_errors=True)
            raise

        logger.info(
            "Packaged LaTeX project for job %s (%d bytes); unresolved deps: %s",
            job_id, zip_path.stat().st_size, report["unresolved"] or "none",
        )
        return zip_path, temp_dir, report
